-- execute following following in Oracle Sql Developer
DROP TABLE PERSON;
DROP SEQUENCE SQ_PERSON;
CREATE TABLE PERSON(
 ID NUMBER(19),
 FIRST_NAME VARCHAR(255),
 LAST_NAME VARCHAR(255),
 ADDRESS VARCHAR(255),
 PRIMARY KEY (ID)
);

CREATE SEQUENCE SQ_PERSON MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 10;

INSERT INTO PERSON VALUES (SQ_PERSON.nextval,'Rose','Kantata', '2736 Kooter Lane');
INSERT INTO PERSON VALUES (SQ_PERSON.nextval,'Mike','Togglie', '111 Cool Dr');
INSERT INTO PERSON VALUES (SQ_PERSON.nextval,'Dana', 'Whitley', '464 Gorsuch Drive');
INSERT INTO PERSON VALUES (SQ_PERSON.nextval,'Robin', 'Cash', '64 Zella Park');
INSERT INTO PERSON VALUES (SQ_PERSON.nextval,'Chary', 'Mess', '112 Yellow Hill');